### ISSUE TITLE
Unable to install helper and unable to list thumb drives. 

### ISSUE THREAD

**Issue by afpena** [nicehash/NHOS-Flash-Tool#12]
Hello there. 

Prompts for install a helper, which is not successfull apparently. Doesn't recognize any thumb drives. Tried wih many, and in two macbooks. 

MacOS 12.0.1

Thanks a lot.

**Comment by usern-spec** [comment]
Fixed in 1.0.7

**Comment by afpena** [comment]
I beg your pardon, but it's still not resolved. Downloaded it from both github and the site itsel, and it still shows as 1.0.6, doenloads the latest image, but never recognizes any of the flash disks I insert, no matter the format.

**Comment by ferdaze** [comment]
I have the same issue. No matter the partition formatting of the 9 drives I have tried the tool never sees anything.
